################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: >-
      Docker Coins
    openshift.io/display-name: 'Docker Coins'
    openshift.io/provider-display-name: 'Sebastian Colomar'
    tags: 'docker,dockercoins'
    version: '1.6'
  name: dockercoins-template
  labels:
    app: dockercoins
message: 'Docker Coins is now deployed.'
objects:
  -
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: rng-ds
    spec:
      selector:
        matchLabels:
          app: rng
      template:
        metadata:
          labels:
            app: rng
        spec:
          containers:
          -
            image: secobau/dockercoins:rng-1.6
            name: rng-container
  -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hasher-deploy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hasher
      template:
        metadata:
          labels:
            app: hasher
        spec:
          containers:
          -
            image: secobau/dockercoins:hasher-1.6
            name: hasher-container
  -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: redis-deploy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: redis
      template:
        metadata:
          labels:
            app: redis
        spec:
          containers:
          -
            image: redis
            name: redis-container
  -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webui-deploy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: webui
      template:
        metadata:
          labels:
            app: webui
        spec:
          containers:
          -
            image: secobau/dockercoins:webui-1.6
            name: webui-container
  -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: worker-deploy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: worker
      template:
        metadata:
          labels:
            app: worker
        spec:
          containers:
          -
            image: secobau/dockercoins:worker-1.6
            name: worker-container
  -
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: hasher-netpol
    spec:
      podSelector:
        matchLabels:
          app: hasher
      ingress:
        -
          from:
            -
              podSelector:
                matchLabels:
                  app: worker
          ports:
            -
              port: 8080
              protocol: TCP
  -
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: redis-netpol
    spec:
      podSelector:
        matchLabels:
          app: redis
      ingress:
        -
          from:
            -
              namespaceSelector:
                matchLabels:
            -
              podSelector:
                matchLabels:
                  app: webui
            -
              podSelector:
                matchLabels:
                  app: worker
          ports:
            -
              port: 6379
              protocol: TCP
  -
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: rng-netpol
    spec:
      podSelector:
        matchLabels:
          app: rng
      ingress:
        -
          from:
            -
              podSelector:
                matchLabels:
                  app: worker
          ports:
            -
              port: 8080
              protocol: TCP
  -
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: worker-netpol
    spec:
      podSelector:
        matchLabels:
          app: worker
      policyTypes:
      - Ingress
  -
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: dockercoins-route
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: webui
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: hasher
    spec:
      ports:
      -
        port: 80
        targetPort: 8080
      selector:
        app: hasher
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: redis
    spec:
      ports:
      -
        port: 6379
      selector:
        app: redis
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: rng
    spec:
      ports:
      -
        port: 80
        targetPort: 8080
      selector:
        app: rng
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: webui
    spec:
      ports:
      -
        port: 80
        targetPort: 8080
      selector:
        app: webui
################################################################################
