export VERSION=stable-4.16;
export RELEASE_ARCH=$(arch);
export RELEASE_IMAGE=$(curl -sL https://mirror.openshift.com/pub/openshift-v4/$RELEASE_ARCH/clients/ocp/$VERSION/release.txt | grep 'Pull From: quay.io' | awk -F ' ' '{print $3}');
export cmd=openshift-baremetal-install;
export pullsecret_file=~/pull-secret.txt;
export extract_dir=~/;
sudo mv /usr/local/bin/oc ~/oc.bak;
curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$VERSION/openshift-client-linux.tar.gz | tar zxvf - oc;
sudo mv oc /usr/local/bin;
sudo mv /usr/local/bin/openshift-baremetal-install ~/openshift-baremetal-install.bak;
oc adm release extract --registry-config "${pullsecret_file}" --command=$cmd --to "${extract_dir}" ${RELEASE_IMAGE};
sudo mv ~/openshift-baremetal-install /usr/local/bin;
export RHCOS_QEMU_URI=$(/usr/local/bin/openshift-baremetal-install coreos print-stream-json | jq -r --arg ARCH "$(arch)" '.architectures[$ARCH].artifacts.qemu.formats["qcow2.gz"].disk.location');
export RHCOS_QEMU_NAME=${RHCOS_QEMU_URI##*/};
export RHCOS_QEMU_UNCOMPRESSED_SHA256=$(/usr/local/bin/openshift-baremetal-install coreos print-stream-json | jq -r --arg ARCH "$(arch)" '.architectures[$ARCH].artifacts.qemu.formats["qcow2.gz"].disk["uncompressed-sha256"]');
curl -L ${RHCOS_QEMU_URI} -o ~/rhcos_image_cache/${RHCOS_QEMU_NAME};
export BAREMETAL_IP=$(ip addr show dev baremetal | awk '/inet /{print $2}' | cut -d"/" -f1);
export BOOTSTRAP_OS_IMAGE="http://${BAREMETAL_IP}:8080/${RHCOS_QEMU_NAME}?sha256=${RHCOS_QEMU_UNCOMPRESSED_SHA256}";
echo "    bootstrapOSImage=${BOOTSTRAP_OS_IMAGE}";
curl -I $BOOTSTRAP_OS_IMAGE;
sed -i 's/^bootstrapOSImage=.*$/bootstrapOSImage='"'$(echo $BOOTSTRAP_OS_IMAGE|sed 's/\//\\\//g')'"/ ./conf.d/install-config_ipmi.conf;
sed -i 's/^bootstrapOSImage=.*$/bootstrapOSImage='"'$(echo $BOOTSTRAP_OS_IMAGE|sed 's/\//\\\//g')'"/ ./conf.d/install-config_redfish.conf;
